---
name: VietNamDongEconomy
description: Thêm hệ thống tiền tệ với đơn vị là Việt Nam Đồng, hỗ trợ điều khiển bằng UI
version: 0.0.1
main: NguyenDuck\VietNamDongEconomy\Main
api: 3.22.5

commands:
  money:
    description: §l§aXem thông tin về tiền của người chơi
    usage: /money
    default: true

permissions:
  VNDEconomy.op:
    default: op
  VNDEconomy.member:
    default: true
...
